// CONTADOR
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_5 = "INCREMENT_5";
export const DECREMENT_5 = "DECREMENT_5";
export const RESET = "RESET";

// SHOPPING CART
export const
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART",
  CLEAR_CART = "CLEAR_CART"

// CRUD
export const
  CREATE_DATA = "CREATE_DATA",
  READ_ALL_DATA = "READ_ALL_DATA",
  UPDATE_DATA = "UPDATE_DATA",
  DELETE_DATA = "DELETE_DATA",
  NO_DATA = "NO_DATA"