import React from "react";

const Loader = () => {
  return (
    <>
      <div className="loadingio-spinner-gear-byn6wv2l1nm">
        <div className="ldio-poh4x3e2ksa">
          <div>
            <div />
            <div />
            <div />
            <div />
            <div />
            <div />
          </div>
        </div>
      </div>
      <style
        type="text/css"
        dangerouslySetInnerHTML={{
          __html:
            "\n@keyframes ldio-poh4x3e2ksa {\n    0% { transform: rotate(0deg) }\n   50% { transform: rotate(22.5deg) }\n  100% { transform: rotate(45deg) }\n}\n.ldio-poh4x3e2ksa > div {\n  transform-origin: 100px 100px;\n  animation: ldio-poh4x3e2ksa 0.2s infinite linear;\n}\n.ldio-poh4x3e2ksa > div div {\n    position: absolute;\n    width: 22px;\n    height: 152px;\n    background: #e15b64;\n    left: 100px;\n    top: 100px;\n    transform: translate(-50%,-50%);\n}\n.ldio-poh4x3e2ksa > div div:nth-child(1) {\n    width: 120px;\n    height: 120px;\n    border-radius: 50%;\n}\n.ldio-poh4x3e2ksa > div div:nth-child(6) {\n    width: 80px;\n    height: 80px;\n    background: #ffffff;\n    border-radius: 50%;\n}.ldio-poh4x3e2ksa > div div:nth-child(3) {\n  transform: translate(-50%,-50%) rotate(45deg)\n}.ldio-poh4x3e2ksa > div div:nth-child(4) {\n  transform: translate(-50%,-50%) rotate(90deg)\n}.ldio-poh4x3e2ksa > div div:nth-child(5) {\n  transform: translate(-50%,-50%) rotate(135deg)\n}\n.loadingio-spinner-gear-byn6wv2l1nm {\n  width: 200px;\n  height: 200px;\n  display: inline-block;\n  overflow: hidden;\n  background: #ffffff;\n}\n.ldio-poh4x3e2ksa {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-poh4x3e2ksa div { box-sizing: content-box; }\n/* generated by https://loading.io/ */\n",
        }}
      />
    </>
  );
};

export default Loader;
